config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'website#index'

    get '/users', to: 'users#index'
    get '/users/:id', to: 'users#show'

    get '/forum', to: 'forum#index'
    match '/forum/:category_id', to: 'forum#category', as: :forum_category, via: [ :get, :post ]
    match '/forum/:category_id/:subcategory_id', to: 'forum#subcategory', as: :forum_subcategory, via: [ :get, :post ]
    match '/forum/:category_id/:subcategory_id/:topic_id', to: 'forum#topic', as: :forum_topic, via: [ :get, :post ]

    get '/messages', to: 'messages#index'
    match '/messages/:convo_id', to: 'messages#convo', as: :convo, via: [ :get, :post ]

    resources :articles
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user && user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard           
      can :manage, :all
    else
      can :read, :all                   # allow everyone to read everything
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  enum language: [:en, :pl, :eo]

  def author
    User.find(user_id)
  end
end

app/models/forum_category.rb
class ForumCategory < ApplicationRecord
  def topics_count(locale)
    count = 0
    ForumSubcategory.where(forum_category_id: id).each do |subcategory|
      count += subcategory.topics_count(locale)
    end
    count
  end

  def last_topic(locale)
    topics = []
    ForumSubcategory.where(forum_category_id: id).each do |subcategory|
      topics << subcategory.last_topic(locale)
    end
    topics.reject! { |x| x.nil? }
    topics.sort_by(&:created_at).last
  end
end

app/models/forum_post.rb
class ForumPost < ApplicationRecord
  belongs_to :user
  belongs_to :forum_topic

  def author
    User.find(user_id)
  end
end

app/models/forum_subcategory.rb
class ForumSubcategory < ApplicationRecord
  belongs_to :forum_category

  def category
    ForumCategory.find(forum_category_id)
  end

  def topics_count(locale)
    ForumTopic.where(forum_subcategory_id: id, language: locale).count
  end

  def last_topic(locale)
    ForumTopic.where(forum_subcategory_id: id, language: locale).order(created_at: :desc).first
  end
end

app/models/forum_topic.rb
class ForumTopic < ApplicationRecord
  belongs_to :forum_subcategory
  enum language: [:en, :pl, :eo]

  def subcategory
    ForumSubcategory.find(forum_subcategory_id)
  end

  def category
    ForumCategory.find(subcategory.forum_category_id)
  end

  def author
    User.find(user_id)
  end

  def last_post
    ForumPost.where(forum_topic_id: id).order(created_at: :desc).first
  end
end

app/models/message.rb
class Message < ApplicationRecord
  def from_user
    User.find(from_id)
  end

  def to_user
    User.find(to_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
  end

  def extract_locale
    parsed_locale = params[:locale]
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.where(language: I18n.locale.to_s)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    #@article.language = params[:language]

    if @article.save
      redirect_to action: 'show', id: @article.id
    else
      render :new
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :language)
    end
end

app/controllers/forum_controller.rb
class ForumController < ApplicationController
  def index
    @categories = ForumCategory.all
  end
  
  def category
    @this_category = ForumCategory.find(params['category_id'])
    @subcategories = ForumSubcategory.where(forum_category_id: params['category_id'])
  end
  
  def subcategory
    @this_category = ForumCategory.find(params['category_id'])
    @this_subcategory = ForumSubcategory.find(params['subcategory_id'])
    @topics = ForumTopic.where(forum_subcategory_id: params['subcategory_id'], language: locale)
  end
  
  def topic
    @this_category = ForumCategory.find(params['category_id'])
    @this_subcategory = ForumSubcategory.find(params['subcategory_id'])
    @this_topic = ForumTopic.find(params['topic_id'])

    if params['commit']
      if params['content'] == ''
        flash.alert = t('alert.post_empty')
      else
        ForumPost.create(user_id: current_user.id, content: params['content'], forum_topic_id: @this_topic.id)
      end
    end

    @posts = ForumPost.where(forum_topic_id: params['topic_id'])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.where(from_id: current_user.id).or(Message.where(to_id: current_user.id))
    @conversations = {}
    @users = {}

    @messages.each do |msg|
      convo_id = msg.from_id == current_user.id ? msg.to_id : msg.from_id
      if @conversations[convo_id]
        @conversations[convo_id] << msg
      else
        @conversations[convo_id] = [ msg ]
        @users[convo_id] = User.find(convo_id)
      end
    end
  end

  def convo
    @convo_id = params[:convo_id]
    @convo_partner = User.find(@convo_id)
    @messages = Message.where(from_id: current_user.id, to_id: @convo_id).or(Message.where(to_id: current_user.id, from_id: @convo_id))

    if params['commit']
      if params['content'] == ''
        flash.alert = t('alert.message_empty')
      else
        Message.create(from_id: current_user.id, to_id: params['convo_id'], content: params['content'])
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])

    if params[:commit].present?
      if params[:nickname].present? && params[:nickname] != @user.nickname
        if User.find_by(nickname: params[:nickname]).nil?
          @user.nickname = params[:nickname]
          flash.notice = t "alert.nickname_changed"
        else
          flash.alert = t "alert.nickname_taken"
        end
      end

      if params[:email].present? && params[:email] != @user.email
        @user.email = params[:email]
        flash.notice = t "alert.email_changed"
      end
    end

    @user.save
  end
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  def index
    @articles = Article.where(language: I18n.locale).order(:created_at, :desc).limit(5)
    @topics = ForumTopic.where(language: I18n.locale).order(:created_at, :desc).limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def path_for_user_profile(user)
    '/' + locale.to_s + '/users/' + user.id.to_s
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.haml
%h1= t('articles.articles')

%hr

%table.forum__table
  %tr
    %th= t("articles.title")
    %th= t("articles.author")
    %th= t("articles.created_at")
  - if @articles.length != 0
    - @articles.each do |article|
      %tr
        %td= link_to article.title, "articles/" + article.id.to_s
        %td= article.author.nickname
        %td= article.created_at
  - else
    %tr
      %td{ colspan: 3 }
        = t 'articles.no_articles'

%hr
= link_to t('articles.new'), new_article_path

app/views/articles/new.haml
%h1
  = t('articles.new')

.articles__new
  = form_with model: @article do |form|
    %div
      = form.label :title, t("form.title")
      %br
      = form.text_field :title
      - @article.errors.full_messages_for(:title).each do |message|
        = message
    %div
      = form.label :body, t("form.body")
      %br
      = form.text_area :body
      - @article.errors.full_messages_for(:body).each do |message|
        = message
    %div
      = form.label :language, t("form.language")
      %br
      = form.select :language, selected: I18n.locale.to_s do
        = options_for_select([['pl', 'pl'], ['en', 'en'], ['eo', 'eo']])
    %div
      = form.submit t("form.create") + ' ' + t('form.article')

app/views/articles/show.haml
%h1
  = @article.title

%p{ style: 'color: gray; margin-top: -30px;' }
  = t('articles.created') + ': ' + @article.created_at.to_s
%p{ style: 'color: gray; margin-top: -30px;' }
  = (t('articles.author') + ': ' + link_to(@article.author.nickname, path_for_user_profile(@article.author))).html_safe
- if @article.author.id == current_user.id
  %a{ style: 'color: red; margin-top: -30px;', id: 'article__delete', href: 'javascript:;', message: t('articles.delete_message') }
    = t('articles.delete')

%p{ style: 'margin-bottom: 50px' }
  = @article.body

= link_to t('articles.list'), articles_path

- content_for :javascript do
  :javascript
    var elem = document.getElementById('article__delete');
    var message = elem.message;

    elem.addEventListener('click', function() {
      if(confirm(message)) {
        $.ajax({
          type: 'DELETE'
        })
      }
    });

app/views/forum/category.haml
%h1
  = link_to t("header.forum"), forum_path
  = " /  " + t("forum.categories." + @this_category.name)

%hr


%table.forum__table
  %tr
    %th= t("forum.subcategory")
    %th= t("forum.topics_number")
    %th= t("forum.last_topic")
  - @subcategories.each do |subcategory|
    %tr
      %td= link_to t("forum.subcategories." + subcategory.name), forum_subcategory_path(locale, @this_category, subcategory)
      %td= subcategory.topics_count(locale)
      %td
        = subcategory.last_topic(locale).nil? ? '-' : link_to(subcategory.last_topic(locale).name, forum_topic_path(locale, subcategory.category, subcategory, subcategory.last_topic(locale)))

app/views/forum/index.haml
%h1
  = t "header.forum"

%hr

%table.forum__table
  %tr
    %th= t("forum.category")
    %th= t("forum.topics_number")
    %th= t("forum.last_topic")
  - @categories.each do |category|
    %tr
      %td= link_to t("forum.categories." + category.name), forum_category_path(locale, category)
      %td= category.topics_count(locale)
      %td
        = category.last_topic(locale).nil? ? '-' : link_to(category.last_topic(locale).name, forum_topic_path(locale, category, category.last_topic(locale).subcategory, category.last_topic(locale)))

app/views/forum/subcategory.haml
%h1
  = link_to t("header.forum"), forum_path
  = " / "
  = link_to t("forum.categories." + @this_category.name), forum_category_path(locale, @this_category)
  = " / " + t("forum.subcategories." + @this_subcategory.name)

%hr

%table.forum__table
  %tr
    %th= t("forum.topic")
    %th= t("forum.author")
    %th= t("forum.last_post")
  - @topics.each do |topic|
    %tr
      %td= link_to t("forum.categories." + topic.name), forum_topic_path(locale, @this_category.id, @this_subcategory.id, topic)
      %td= link_to topic.author.nickname, path_for_user_profile(topic.author)
      %td
        = link_to topic.last_post.author.nickname, users_path(locale, topic.last_post.author)
        = ", " + topic.last_post.created_at.to_s

app/views/forum/topic.haml
%h1.forum__navigation
  = link_to t("header.forum"), forum_path
  = " / "
  = link_to t("forum.categories." + @this_category.name), forum_category_path(locale, @this_category)
  = " / "
  = link_to t("forum.subcategories." + @this_subcategory.name), forum_subcategory_path(locale, @this_category, @this_subcategory)
  = " / " + @this_topic.name


- @posts.each do |post|
  %hr
  %h2{ style: "margin-bottom: 5px;" }= link_to post.author.nickname, path_for_user_profile(post.author)
  %h6{ style: "margin-top: 5px;" }= post.created_at
  %p= post.content
  %br

%hr

%h1= t('forum.new_post')
= form_with do |form|
  = form.text_area :content, class: 'forum__textarea'
  %br
  = form.submit class: 'forum__post-submit'

app/views/layouts/application.haml
!!! 5

%head
  %title= Vojo
  %meta{ name: "viewport", content: "width=device-width,initial-scale=1" }
  = csrf_meta_tags
  = csp_meta_tag

  %link{ rel: "preconnect", href: "https://fonts.googleapis.com" }
  %link{ rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: true }
  %link{ href: "https://fonts.googleapis.com/css2?family=Ubuntu&display=swap", rel: "stylesheet" }

  %link{ rel: "stylesheet", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css", integrity: "sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T", crossorigin: "anonymous" }
  %link{ rel: "stylesheet", href: "https://unpkg.com/leaflet@1.7.1/dist/leaflet.css", integrity: "sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==", crossorigin: "" }

  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

%body
  = render partial: 'shared/header', locals: { alert: alert, notice: notice }
  .main-container
    = yield
  = render partial: 'shared/footer'

  %script{ src: "https://code.jquery.com/jquery-3.6.0.min.js", integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=", crossorigin: "anonymous" }
  %script{ src: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js", integrity: "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1", crossorigin: "anonymous" }
  %script{ src: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js", integrity: "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", crossorigin: "anonymous" }
  %script{ src: "https://unpkg.com/leaflet@1.7.1/dist/leaflet.js", integrity: "sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==", crossorigin: "" }
  = yield :javascript

app/views/messages/convo.haml
%h1
  = t("messages.convo_with") + @convo_partner.nickname

- @messages.each do |msg|
  - if msg.to_user == current_user
    .messages__box-container--left
      .messages__box--left
        .messages__author-container
          = msg.from_user.nickname + ","
          = time_ago_in_words(msg.created_at)
          = t "messages.ago"
        = msg.content
  - else
    .messages__box-container--right
      .messages__box--right
        .messages__author-container
          = msg.from_user.nickname + ","
          = time_ago_in_words(msg.created_at)
          = t "messages.ago"
        = msg.content

= form_with method: :post do |f|
  = f.text_area :content, class: 'forum__textarea'
  %br
  = f.submit class: 'forum__post-submit'

:javascript
  document.getElementById('content').scrollIntoView();

app/views/messages/index.haml
%h1
  = t "messages.recent_conversations"

%hr

%table.forum__table
  %tr
    %th= t("messages.username")
    %th= t("messages.last_message")
    %th= t("messages.time")
  - @conversations.each do |convo_id|
    - convo = @conversations[convo_id[0]]
    %tr
      %td= link_to (convo.last.from_id == current_user.id ? convo.last.to_user.nickname : convo.last.from_user.nickname), "messages/" + convo_id[0].to_s
      %td= convo.last.content[0,50] + "..."
      %td= convo.last.created_at

app/views/shared/_footer.haml
%footer.main-footer
  

app/views/shared/_header.haml
%header.main-header
  .main-header__container
    = link_to :root, class: 'main-header__logo' do
      = image_tag 'logo.png', height: 40

    .main-header__alert-notice-container
      .main-header__alert
        = alert
      .main-header__notice
        = notice

    .main-header__links
      = link_to t("header.articles"), articles_path
      = link_to t("header.forum"), forum_path
      .main-header__dropdown
        .main-header__dropdown-button--icon
          %svg{ width: 32, height: 32, fill: "white", viewBox: "0 0 16 16", style: "width: 32px", preserveAspectRatio: "xMidYMid meet"}
            %path{ d: "M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" }
        .main-header__dropdown-content
          - if current_user.nil?
            = link_to t("header.login"), "/users/sign_in"
          - else
            = link_to t("header.messages"), messages_path
            = link_to t("header.account"), path_for_user_profile(current_user)
            = link_to t("header.users"), users_path()
            = link_to t("header.logout"), destroy_user_session_path, method: :delete
      .main-header__dropdown
        .main-header__dropdown-button
          = t "header.lang"
        .main-header__dropdown-content
          = link_to "Polski", { locale: "pl" }
          = link_to "English", { locale: "en" }
          = link_to "Esperanto", { locale: "eo" }
.main-header-spacer

app/views/users/index.haml
%h2
  users index

%table
  %thead
    %tr
      %th ID
      %th= t "users.email"
      %th= t "users.actions"
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.email
        %td
          = link_to t("users.profile"), "/" + I18n.locale.to_s + "/users/" + user.id.to_s

app/views/users/show.haml
= form_with method: :get do |f|
  %table.forum__table
    %tr
      %th{ colspan: "2" }
        = t 'users.user_details'
    %tr
      %td ID
      %td= @user.id
    %tr
      %td= t 'users.username'
      %td
        - if current_user.id == @user.id
          = f.text_field :nickname, value: @user.nickname, style: "width: 100%"
        - else
          = @user.nickname
    %tr
      %td= t 'users.email'
      %td
        - if current_user.id == @user.id
          = f.email_field :email, value: @user.email, style: "width: 100%"
        - else
          = @user.email
    - if current_user.id == @user.id
      %tr
        %td{ colspan: "2" }
          = f.submit style: "display: block; margin: auto", class: "btn btn-dark"

app/views/website/index.haml
%h1= t 'home.newest_articles'
- if @articles.empty?
  = t 'articles.no_articles'
- else
  - @articles.each do |article|
    = article.title
    = link_to t('home.visit'), "#{I18n.locale}/articles/#{article.id}"
    %br

%hr

%h1= t 'home.newest_topics'
- if @articles.empty?
  = t 'forum.no_topics'
- else
  - @topics.each do |topic|
    = topic.name
    = link_to t('home.visit'), "#{I18n.locale}/forum/#{topic.category.id}/#{topic.forum_subcategory_id}/#{topic.id}"
    %br